{
   gROOT->ProcessLine(".L NQR.C+");
   TChain *AutoTree = new TChain ("AutoTree");
   /******* NMR Runs ********/
   //AutoTree->Add("root-files/r0096.root");
   //AutoTree->Add("root-files/32Al/*.root");
   //AutoTree->Add("root-files/r0125.root");
   //AutoTree->Add("root-files/r0127.root");
   //AutoTree->Add("root-files/r0128.root");
   //AutoTree->Add("root-files/r0129.root");
   //AutoTree->Add("root-files/r0131.root");
   //AutoTree->Add("root-files/r0132.root");
   //AutoTree->Add("root-files/r0133.root");
   //AutoTree->Add("root-files/r0135.root");
   //AutoTree->Add("root-files/r0136.root");
   //AutoTree->Add("root-files/r0137.root");
   //AutoTree->Add("root-files/r0138.root");
   //AutoTree->Add("root-files/r0139.root");
   //AutoTree->Add("root-files/r0140.root");
   //AutoTree->Add("root-files/r0141.root");
   //AutoTree->Add("root-files/r0142.root");
   //AutoTree->Add("root-files/r0143.root");
   //AutoTree->Add("root-files/r0145.root");
   //AutoTree->Add("root-files/r0146.root");
   //AutoTree->Add("root-files/r0157.root");
   //AutoTree->Add("root-files/r0158.root");
   //AutoTree->Add("root-files/r0159.root");
   //AutoTree->Add("root-files/r0160.root");
   //AutoTree->Add("root-files/r0164.root");
   //AutoTree->Add("root-files/r0165.root");
   //AutoTree->Add("root-files/r0166.root");
   //AutoTree->Add("root-files/r0167.root");
   //AutoTree->Add("root-files/r0169.root");
   //AutoTree->Add("root-files/r0170.root");
   //AutoTree->Add("root-files/r0171.root");
   //AutoTree->Add("root-files/r0172.root");
   //AutoTree->Add("root-files/r0173.root");
   //AutoTree->Add("root-files/r0174.root");
   //AutoTree->Add("root-files/r0175.root");
   //AutoTree->Add("root-files/r0176.root");
   //AutoTree->Add("root-files/r0177.root");
   //AutoTree->Add("root-files/r0179.root");
   //AutoTree->Add("root-files/r0180.root");
   //AutoTree->Add("root-files/r0181.root");
   //AutoTree->Add("root-files/r0184.root");
   //AutoTree->Add("root-files/r0185.root");
   //AutoTree->Add("root-files/r0186.root");
   //AutoTree->Add("root-files/r0187.root");

   /******* NQR Runs ********/
   //AutoTree->Add("root-files/r0107.root");
   AutoTree->Add("root-files/r0193.root");
   AutoTree->Add("root-files/r0194.root");
   AutoTree->Add("root-files/r0195.root");
   AutoTree->Add("root-files/r0197.root");
   AutoTree->Add("root-files/r0199.root");
   AutoTree->Add("root-files/r0203.root");
   AutoTree->Add("root-files/r0204.root");
   AutoTree->Add("root-files/r0205.root");
   AutoTree->Add("root-files/r0206.root");
   AutoTree->Add("root-files/r0207.root");
   AutoTree->Add("root-files/r0208.root");
   AutoTree->Add("root-files/r0209.root");

   NQR *t = new NQR("",AutoTree);
   t->ReadPara("NMR_NQR.in");
   t->Loop();
   t->MakeNQR();
   TCanvas *c1 = new TCanvas("c1","c1",0,0,800,1000);
   c1->Divide(1,2);
   c1->cd(1);
   t->gNQR->Draw("AP");
   c1->cd(2);
   t->gTiD3_T->Draw("APL");
   t->gTiD3_T_cut->Draw("PL");
}
